version: '3.7'


services:
  tria-redis:
    # image: redis/redis-stack-server
    image: redis/redis-stack
    container_name: tria-redis
    # command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]  # disable persistence
    ports:
      - 6379:6379
      - 8001:8001
    # env_file:
    #   - .env
    environment:
      - REDIS_ARGS="--save ''"
    restart: "on-failure"
    networks:
      - triabot

  tria-composite:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-composite
    command: ["poetry", "run", "python", "tria_bot/composite.py"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-tickers:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-tickers
    command: ["poetry", "run", "python", "tria_bot/tickers.py"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot
  
  tria-gaps:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-gaps
    command: ["poetry", "run", "python", "tria_bot/gaps.py"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
      - tria-tickers
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-depth-1:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-depth-1
    command: ["poetry", "run", "python", "tria_bot/depth.py", "--splitter=1/3"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-depth-2:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-depth-2
    command: ["poetry", "run", "python", "tria_bot/depth.py", "--splitter=2/3"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-depth-3:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-depth-3
    command: ["poetry", "run", "python", "tria_bot/depth.py", "--splitter=3/3"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-proffit:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-proffit
    command: ["poetry", "run", "python", "tria_bot/proffit.py", "--strict"]
    # command: ["poetry", "run", "python", "tria_bot/proffit.py", "--no-strict"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-arbitrage:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-arbitrage
    command: ["poetry", "run", "python", "tria_bot/arbitrage.py"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
      - tria-proffit
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

networks:
  triabot: