version: '3.7'


services:
  tria-redis:
    image: redis/redis-stack
    # image: redis/redis-server
    container_name: tria-redis
    # command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]  # disable persistence
    ports:
      - 6379:6379
      - 8001:8001
    # env_file:
    #   - .env
    environment:
      - REDIS_ARGS="--save ''"
    restart: "on-failure"
    networks:
      - triabot

  tria-composite:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-composite
    command: ["poetry", "run", "python", "tria_bot/composite.py"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-tickers:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-tickers
    command: ["poetry", "run", "python", "tria_bot/tickers.py"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-depth-strong-stable:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-depth-strong-stable
    command: ["poetry", "run", "python", "tria_bot/depth.py", "--kind=strong_stable"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-depth-alt-stable:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-depth-alt-stable
    command: ["poetry", "run", "python", "tria_bot/depth.py", "--kind=alt_stable"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-depth-alt-btc:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-depth-alt-btc
    command: ["poetry", "run", "python", "tria_bot/depth.py", "--kind=alt_strong", "--strong=BTC"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-depth-alt-bnb:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-depth-alt-bnb
    command: ["poetry", "run", "python", "tria_bot/depth.py", "--kind=alt_strong", "--strong=BNB"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot

  tria-depth-alt-eth:
    image: tria-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tria-depth-alt-eth
    command: ["poetry", "run", "python", "tria_bot/depth.py", "--kind=alt_strong", "--strong=ETH"]
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - tria-redis
      - tria-composite
    volumes:
      - ./tria_bot:/app/tria_bot
    networks:
      - triabot


networks:
  triabot: